# Site settings
name: Team Grape
email: 513296161@qq.com
author: YangyuGao
url: https://yangyugao.github.io
resume_site: 
github: https://github.com/YangyuGao/
baseurl: ''
description: 'Welcome to Group V'
meta_description: Group V; GRP blog
motto: It's our wits that make us men.
banner: <a href="http://github.com/grapeunnc/algodomino">github repo</a>

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: YangyuGao
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : shiki
    disqus :
        short_name : Mei
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light